### ISSUE TITLE
Works?

### ISSUE THREAD

**Issue by NycuRO** [haniokasai/SynapseAPI-maven#1]
Hello. This work?

**Comment by NycuRO** [comment]
@haniokasai Not work. You can add file .jar?

**Comment by haniokasai** [comment]
it work.
you can download from
jenkins.haniokasai.com/job/SynapseAPI/

**Comment by haniokasai** [comment]
http://jenkins.haniokasai.com/job/SynapseAPI/18/console

**Comment by NycuRO** [comment]
@haniokasai With your synapse players cannot break blocks.

**Comment by haniokasai** [comment]
enter /gamemode 1,/gamemode 0 and /gamemode <your favorite gamemode> ,and you can break or place block.

**Comment by NycuRO** [comment]
@haniokasai Wtf. You have one plugin for players?

**Comment by haniokasai** [comment]
no. i can write,however i dont need to write it.
